# This file was generated by GoReleaser. DO NOT EDIT.
cask "pv-migrate" do
  version "3.6.2"

  on_macos do
    on_arm do
      sha256 "43727d692842dad8c01a94ca39b2c952856171fe77b015f74fdb292ebf4e3357"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "930f18bfce93c33b60cca6abdcbde52287be26de398081e4fed135156fa00714"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f6200027259a76fdca5bd990a5802d462854ae09a00c43d828eeb4dacb8eb547"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "edc5f1d4c28d8bde62ba61d4d92485e835f01333688af1fb8c0705cbe9b96367"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_linux_x86_64.tar.gz"
    end
  end

  name "pv-migrate"
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pv-migrate"
  bash_completion "completions/pv-migrate.bash"
  fish_completion "completions/pv-migrate.fish"
  zsh_completion "completions/pv-migrate.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pv-migrate"]
    end
  end

  # No zap stanza required
end
