# This file was generated by GoReleaser. DO NOT EDIT.
cask "pv-migrate" do
  version "3.6.1"

  on_macos do
    on_intel do
      sha256 "caf2a3e4faa0b78241e5648ad645e6f2d152bc8dac1d7eec8cf7e8d9c90177bc"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f99e86c04d07848d03a23eee9acc4ba39f7a3cf1d2742baa06fd7c9aa28e9821"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eeb2e88d0ebea7c3705db0e534c056c1cd4ec2fd8c8ba3e18a74f485dc8c26b2"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9ab436961fe5b5b0f49f032c064f0a6f16577ea42ba57f69ba87e2c822fef933"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "pv-migrate"
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pv-migrate"
  bash_completion "completions/pv-migrate.bash"
  fish_completion "completions/pv-migrate.fish"
  zsh_completion "completions/pv-migrate.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pv-migrate"]
    end
  end

  # No zap stanza required

end
