# This file was generated by GoReleaser. DO NOT EDIT.
cask "pv-migrate" do
  version "3.5.0"

  on_macos do
    on_intel do
      sha256 "7cf8918d96c62447663a3585dcec95b1bc4460959708b1999206db5780f3cab0"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "72f4db67e02c6f6dff3f1b6c5551eafa090eb013033dfdb5808e5afdf5b79e4c"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c98f2f4590b4dae9d9e4698fb6397644531ad4986e4f6abee7f2fc43fad829f"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8d994fc0c2c78171868c486bf9ec4cd5535ea1bf356d4e5d586677b67c2ee047"
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v#{version}/pv-migrate_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "pv-migrate"
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pv-migrate"
  bash_completion "completions/pv-migrate.bash"
  fish_completion "completions/pv-migrate.fish"
  zsh_completion "completions/pv-migrate.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pv-migrate"]
    end
  end

  # No zap stanza required

end
