# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PvMigrate < Formula
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"
  version "1.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v1.6.1/pv-migrate_v1.6.1_darwin_x86_64.tar.gz"
      sha256 "4ff56e45226bf258eb1740651c25178f8abd55298cd7bb873065f5eeb7b77a7f"

      def install
        bin.install "pv-migrate"
        bash_completion.install "completions/pv-migrate.bash" => "pv-migrate"
        zsh_completion.install "completions/pv-migrate.zsh" => "_pv-migrate"
        fish_completion.install "completions/pv-migrate.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v1.6.1/pv-migrate_v1.6.1_darwin_arm64.tar.gz"
      sha256 "fe6ea5c66f286a821d6fb1833c1f7330e630a31467be99e9e602611871179130"

      def install
        bin.install "pv-migrate"
        bash_completion.install "completions/pv-migrate.bash" => "pv-migrate"
        zsh_completion.install "completions/pv-migrate.zsh" => "_pv-migrate"
        fish_completion.install "completions/pv-migrate.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v1.6.1/pv-migrate_v1.6.1_linux_arm64.tar.gz"
      sha256 "88492cc096c84597ab937b60831cfa506e7f7c78a04deae48bb63d4e10fc54f4"

      def install
        bin.install "pv-migrate"
        bash_completion.install "completions/pv-migrate.bash" => "pv-migrate"
        zsh_completion.install "completions/pv-migrate.zsh" => "_pv-migrate"
        fish_completion.install "completions/pv-migrate.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v1.6.1/pv-migrate_v1.6.1_linux_armv7.tar.gz"
      sha256 "9704e150db6cc00a53280e6810c70465051019cd9fa4918e8eeb38609955d876"

      def install
        bin.install "pv-migrate"
        bash_completion.install "completions/pv-migrate.bash" => "pv-migrate"
        zsh_completion.install "completions/pv-migrate.zsh" => "_pv-migrate"
        fish_completion.install "completions/pv-migrate.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v1.6.1/pv-migrate_v1.6.1_linux_x86_64.tar.gz"
      sha256 "e4db53a08b739d0b6798d86748a4e59b5f0734a0b8ff5e4545f4f9af0786cf9b"

      def install
        bin.install "pv-migrate"
        bash_completion.install "completions/pv-migrate.bash" => "pv-migrate"
        zsh_completion.install "completions/pv-migrate.zsh" => "_pv-migrate"
        fish_completion.install "completions/pv-migrate.fish"
      end
    end
  end

  test do
    system "#{bin}/pv-migrate -v"
  end
end
