# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PvMigrate < Formula
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.7.0/pv-migrate_0.7.0_darwin_x86_64.tar.gz"
      sha256 "b1f639c6baa5333ece40cc43524b219b520e427620f2a2e0cdfa6e83f011e515"

      def install
        bin.install "pv-migrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.7.0/pv-migrate_0.7.0_darwin_arm64.tar.gz"
      sha256 "fa6fe951628c9e8707e2f3abe086e30cd7a36ddc1ab294c7a3f09a3743f0e028"

      def install
        bin.install "pv-migrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.7.0/pv-migrate_0.7.0_linux_arm64.tar.gz"
      sha256 "14e6d1b8fe52f99771be5755e164db326c835ed819137157985c0b8dcf74fefc"

      def install
        bin.install "pv-migrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.7.0/pv-migrate_0.7.0_linux_x86_64.tar.gz"
      sha256 "2f35b6cccc011209d01b040a9bbd0a81cf7cf8816c7e8119349c18e7ff7bcea9"

      def install
        bin.install "pv-migrate"
      end
    end
  end

  test do
    system "#{bin}/pv-migrate -v"
  end
end
