# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PvMigrate < Formula
  desc "Persistent volume migration plugin for Kubernetes"
  homepage "https://github.com/utkuozdemir/pv-migrate"
  version "0.6.0"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.6.0/pv-migrate_0.6.0_darwin_x86_64.tar.gz"
      sha256 "58c468bc2084e183a0a9ab5938a47117892c20c2768203fd286998f25c97c0bc"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.6.0/pv-migrate_0.6.0_linux_x86_64.tar.gz"
      sha256 "543d0b788ef06c549673c798d0a06a3d38fd85d9bce0d328fe99624a53769837"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkuozdemir/pv-migrate/releases/download/v0.6.0/pv-migrate_0.6.0_linux_arm64.tar.gz"
      sha256 "42a419e762e0768156576cb5bfe93a209280186796ba068ee856088af5a27c5f"
    end
  end

  def install
    bin.install "pv-migrate"
  end

  test do
    system "#{bin}/pv-migrate -v"
  end
end
