---
name: install
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
env:
  HOMEBREW_NO_ANALYTICS: "1"
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Install homebrew
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
      - name: Brew tap
        run: brew tap utkuozdemir/pv-migrate
      - name: Brew install
        run: brew install pv-migrate
      - name: Run command
        run: pv-migrate --version
