---
name: install
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04
    steps:
      - name: Install homebrew
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /root/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - name: Brew tap
        run: brew tap utkuozdemir/pv-migrate
      - name: Brew install
        run: brew install pv-migrate
      - name: Run command
        run: pv-migrate --version
